### ISSUE TITLE
Create modals in create subscription

### ISSUE THREAD

**Issue by ialberquilla** [Libree/superfluid-tokenized-ida#90]
When this PR #88  is merged, create subscription will be implemented with the vars using wagmi to know when a tx has been confirm.

When the user clicks submit, a modal should open to inform that the transaction should be approved in wallet. When approve change to spinner to let know that is mining, and when mining change to a confirmation in the modal. When accept is clicked in the modal, should redirect to subscriptions

**Comment by valentinnavalos** [comment]
STATUS: working on handle tx modal on buying & selling subs.
